In [3]:
import pandas as pd
import numpy as np

In [4]:
dataset=pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/supplement.csv")
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   ID             188340 non-null  object 
 1   Store_id       188340 non-null  int64  
 2   Store_Type     188340 non-null  object 
 3   Location_Type  188340 non-null  object 
 4   Region_Code    188340 non-null  object 
 5   Date           188340 non-null  object 
 6   Holiday        188340 non-null  int64  
 7   Discount       188340 non-null  object 
 8   #Order         188340 non-null  int64  
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB


In [6]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [7]:
dataset.describe()

Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [8]:
pip install plotly

In [9]:
import plotly.express as px


In [11]:
pie1=dataset["Store_Type"].value_counts()
store=pie1.index
orders=pie1.values
fig=px.pie(dataset,values=orders,names=store)
fig.show()

In [12]:
pie2=dataset["Location_Type"].value_counts()
location=pie2.index
orders=pie2.values
fig=px.pie(dataset,values=orders,names=location)
fig.show()

In [14]:
pie3=dataset["Discount"].value_counts()
Discount=pie3.index
orders=pie3.values
fig=px.pie(dataset,values=orders,names=Discount)
fig.show()

In [15]:
pie4=dataset["Holiday"].value_counts()
Holiday=pie4.index
orders=pie4.values
fig=px.pie(dataset,values=orders,names=Holiday)
fig.show()

In [16]:
dataset["Discount"]=dataset["Discount"].map({"Yes":1,"No":0})


In [17]:
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [72]:
# similar way we do for the rest of the features
dataset["Store_Type"]=dataset["Store_Type"].map({"S1":1,"S2":2,"S3":3,"S4":4})
dataset["Location_Type"]=dataset["Location_Type"].map({"L1":1,"L2":2,"L3":3,"L4":4,"L5":5})
dataset["Region_Code"]=dataset["Region_Code"].map({"R1":1,"R2":2,"R3":3,"R4":4})

In [73]:
dataset

ID  Store_id  Store_Type  Location_Type  Region_Code  \
0       T1000001         1           1              3            1   
1       T1000002       253           4              2            1   
2       T1000003       252           3              2            1   
3       T1000004       251           2              3            1   
4       T1000005       250           2              3            4   
...          ...       ...         ...            ...          ...   
188335  T1188336       149           2              3            2   
188336  T1188337       153           4              2            1   
188337  T1188338       154           1              3            2   
188338  T1188339       155           3              1            2   
188339  T1188340       152           2              1            1   

              Date  Holiday  Discount  #Order     Sales  Store_type  Location  \
0       2018-01-01        1         1       9   7011.84           1         3   
1       2018-01-01        1         1      60  51789.12           4         2   
2       2018-01-01        1         1      42  36868.20           3         2   
3       2018-01-01        1         1      23  19715.16           2         3   
4       2018-01-01        1         1      62  45614.52           2         3   
...            ...      ...       ...     ...       ...         ...       ...   
188335  2019-05-31        1         1      51  37272.00           2         3   
188336  2019-05-31        1         0      90  54572.64           4         2   
188337  2019-05-31        1         0      56  31624.56           1         3   
188338  2019-05-31        1         1      70  49162.41           3         1   
188339  2019-05-31        1         0      47  37977.00           2         1   

        Location_type  
0                   3  
1                   2  
2                   2  
3                   3  
4                   3  
...               ...  
188335              3  
188336              2  
188337              3  
188338              1  
188339              1  

[188340 rows x 13 columns]

In [75]:
#now model creation
#spliting the dependent and independent variables from the dataset
x=np.array(dataset[["Region_Code","Store_Type","Location_Type","Holiday","Discount"]])
y=np.array(dataset["#Order"])

In [76]:
X

array([[1, 3, 1, 1],
       [4, 2, 1, 1],
       [3, 2, 1, 1],
       ...,
       [1, 3, 1, 0],
       [3, 1, 1, 1],
       [2, 1, 1, 0]])

In [82]:
Y

array([ 9, 60, 42, ..., 56, 70, 47])

In [78]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.23,random_state=42)

In [79]:
print("                         *****x_train values:****")
x_train

                         *****x_train values:****


array([[1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 4, 1, 1],
       ...,
       [4, 1, 1, 0, 1],
       [3, 1, 3, 0, 1],
       [2, 2, 4, 0, 0]])

In [80]:
print("           *****x_test values:****")
x_test

           *****x_test values:****


array([[1, 1, 4, 0, 0],
       [1, 4, 2, 1, 1],
       [3, 1, 1, 0, 1],
       ...,
       [2, 1, 5, 0, 0],
       [4, 2, 3, 0, 0],
       [3, 1, 1, 0, 1]])

In [83]:
 print("*****y_train values:****")
y_train

*****y_train values:****


array([54, 68,  5, ..., 51, 55, 51])

In [84]:
print("*****Y_test values:****")
y_test

*****Y_test values:****


array([ 54, 111,  59, ...,  41,  28,  90])

In [85]:
import lightgbm as lgb
model=lgb.LGBMRegressor()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

y_pred

/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013069 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 20
[LightGBM] [Info] Number of data points in the train set: 145021, number of used features: 5
[LightGBM] [Info] Start training from score 68.152695


/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



array([ 50.28246073, 103.91866499,  68.09996279, ...,  43.89576282,
        39.07794444,  68.09996279])

In [86]:
y_test

array([ 54, 111,  59, ...,  41,  28,  90])

In [87]:
# Testing and trainging accuracies
accuracy1=model.score(x_train,y_train)
print("The  training accuracy is ",accuracy1)
accuracy2=model.score(x_test,y_test)
print("The  testing accuracy is ",accuracy2)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



The  training accuracy is  0.6160256190512118


/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



The  testing accuracy is  0.6121113080281403


In [88]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

Mean Squared Error: 362.06172782138617


In [89]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=0,max_depth=4)
dt.fit(x_train,y_train)
y_pred1=dt.predict(x_test)
y_pred1

array([ 51, 111,  63, ...,  51,  37,  63])

In [90]:
y_test

array([ 54, 111,  59, ...,  41,  28,  90])

In [91]:
print("the difference between the y_predicted and y_actural for decision algo")
y_pred1-y_test

the difference between the y_predicted and y_actural for decision algo


array([ -3,   0,   4, ...,  10,   9, -27])

In [92]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred1)
print('Mean Squared Error:', mse)

Mean Squared Error: 446.9775848934648


In [94]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012133 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 20
[LightGBM] [Info] Number of data points in the train set: 145021, number of used features: 5
[LightGBM] [Info] Start training from score 68.152695


/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



array([ 50.28246073, 103.91866499,  68.09996279, ...,  43.89576282,
        39.07794444,  68.09996279])

In [95]:
y_test

array([ 54, 111,  59, ...,  41,  28,  90])

In [97]:
data=pd.DataFrame({"predicted Orders":y_pred.flatten()})
data

predicted Orders
0             50.282461
1            103.918665
2             68.099963
3             84.756411
4             55.672340
...                 ...
43314         84.528976
43315         54.798357
43316         43.895763
43317         39.077944
43318         68.099963

[43319 rows x 1 columns]